#!/bin/bash
SERVER_AD="$SERVER_AD"
PORT="2223"
echo "Clinte TURIP"
echo "(1= SEND: Handshake HOLI_TURIP"
echo "HOLT_TURIP 127.0.0.1" | nc $SERVER_AD $PORT
echo "(2) LISTEN: Comprobación Handshake"


MSG=`nc -1 "$PORT"`
if  [ "$MSG" != "OK_TURIP" ]
then 
    echo "ERROR 1: Handshake incorrecto"
	exit 1

fi
echo "(5= SEND: Nombre de archivo"
echo "FILE_NAME vaca.vaca" | nc $SERVER_AD $PORT
echo "(6) LISTEN: Comprobación nombre de archivo"
MSG=`nc -1 $PORT`


exit 0


